### ISSUE TITLE
[Bug] 缩放会导致窗口右侧以及下方产生黑白闪烁的区域

### ISSUE THREAD

**Issue by pchpub** [Lukoning/ZoomNCM#1]
![image](https://github.com/user-attachments/assets/0416c10a-2a11-455f-84e4-dcf17d006f72)

**Comment by Lukoning** [comment]
试着调整一下窗口大小？我没法复现

**Comment by Lukoning** [comment]
0.2版本用了一个完全不同的方法调整缩放
应该可以解决问题……
